### ISSUE TITLE
Compatibility for PSVITA?

### ISSUE THREAD

**Issue by KronoTrigger** [Yukikamome316/MCSE-Editor#1]
Hello there! I know that the application says that it is specifically for the Wii U and it works great, but you're the only developers I have seen create a tool designed for editing this type of file. If you are fine with the request, do you mind creating a tool that also allows for editing the PSVITA's ".msscmp" file? 

* Thank you!

**Comment by yukikamome316** [comment]
Thank you for your message. I'm glad to hear that. By the way, I guess each Minecraft console editions have common ".msscmp" files of format, and therefore you may be able to edit them with this software; you will make it recognize PSVITA's file as Wii U's one. Please contact me again if it doesn't work well.

**Comment by KronoTrigger** [comment]
Unfortunately, it didn't work for the PSVITA's '.msscmp' file. Is there any way I can make the app recognize the PSVITA file as a Wii U file, I'm unsure on how to do so. 

*Thank you!

**Comment by EliMCGamerGuy** [comment]
chances are it'll be like PCK files, a different format per system. it's confusing that they used the same file extension, but that's just how 4J Studios made it.

**Comment by syoch** [comment]
Thanks for the bug report.
We now know why we cannot parse Vita's msscmp.
We plan to support parsing Vita msscmp in a future update.

However, there is a problem that the sound in the game becomes strange when it is rewritten with binka of a different size, which is also a problem on the Wii U.
So please make a backup of the original msscmp before you actually use this tool to introduce the modified msscmp into your game.

(Used DeepL translator)

**Comment by syoch** [comment]
PS Vita's msscmp parse is supported in version 2.0(pre-release).
link: [MCSE-Editor 2.0](https://github.com/yukikamome316/MCSE-Editor/releases/tag/2.0)
